filtre travel back
abdelchag/blasacar-back pull request #10
Opened 2021-04-19 17:50 UTC by misbahimed

2021-04-19 18:53 UTC, aminebarrima commented on BlasaCar-back/blasa.travel.web/Controllers/TravelController.cs
> +        public async Task<IActionResult> SearchTravel(string arrivalCity, string departureCity, string departureDate, string departureTime,
pour la signature de la méthode search , tu as mis tous les paramètres obligatoires, sauf qu'on pourra y avoir des optionnelles, je pense que ça serait mieux d'utiliser un dto de type filtreTravel avec tous les champs de recherche, et de le mapper par la suite avec l'objet entité de Travel

2021-04-19 18:53 UTC, aminebarrima requested changes
pour la signature de la méthode search , tu as mis tous les paramètres obligatoires, sauf qu'on pourra y avoir des optionnelles, je pense que ça serait mieux d'utiliser un dto de type filtreTravel avec tous les champs de recherche, et de le mapper par la suite avec l'objet entité de Travel

2021-09-15 18:45 UTC, abdelchag approved these changes

2021-09-18 14:28 UTC, aminebarrima approved these changes

2021-09-18 14:28 UTC, merged